### PR TITLE
Revert "remove MinifiedHeaders from ASF-Release.cfg"

### PR DESCRIPTION
**Pull request by dgrove-oss**
Reverts apache/incubator-openwhisk-utilities#65

### CODE REVIEW

**Comment by rabbah** [comment]
pourquois?

**Comment by dgrove-oss** [comment]
i thought I had broken main repo per your comment on dev list and was going to revert and try again later.  but we could fix up main repo instead.  either is fine.  i'm in meetings most of the rest of today, so didn't want to block things...

**Comment by rabbah** [comment]
Opps. Sorry. The main repo is not broken. The mini licenses in tests/dat/actions are not caught because that whole dir is excluded in the scan code config. We need to fix both (remove the exclusion and fix the headers).

**Comment by dgrove-oss** [comment]
got it.  will close this then.

**Pull request closed without merging**
